name: saverecipes
description: A new Flutter application to save cooking recipes

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.0+3
  image_picker: ^0.7.4
  mockito: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true